- platform: modbus
  registers:
  - name: conext_sw_device_state_raw
    hub: combox
    slave: 90
    register: 0x0040
    data_type: uint
  - name: conext_sw_device_present_raw
    hub: combox
    slave: 90
    register: 0x0041
    data_type: uint
  - name: conext_sw_inverter_enabled_raw
    hub: combox
    slave: 90
    register: 0x0042
    data_type: uint
  - name: conext_sw_charger_enabled_raw
    hub: combox
    slave: 90
    register: 0x0043
    data_type: uint
  - name: conext_sw_active_faults_flag_raw
    hub: combox
    slave: 90
    register: 0x0044
    data_type: uint
  - name: conext_sw_active_warnings_flag_raw
    hub: combox
    slave: 90
    register: 0x0045
    data_type: uint
  - name: conext_sw_charge_mode_status_raw
    hub: combox
    slave: 90
    register: 0x0046
    data_type: uint
  - name: conext_sw_fault_bitmap_0_raw
    hub: combox
    slave: 90
    register: 0x0047
    data_type: uint
  - name: conext_sw_fault_bitmap_1_raw
    hub: combox
    slave: 90
    register: 0x0048
    data_type: uint
  - name: conext_sw_fault_bitmap_2_raw
    hub: combox
    slave: 90
    register: 0x0049
    data_type: uint
  - name: conext_sw_inverter_warning_bitmap_0_raw
    hub: combox
    slave: 90
    register: 0x004A
    data_type: uint
  - name: conext_sw_inverter_status_raw
    hub: combox
    slave: 90
    register: 0x004B
    data_type: uint
  - name: conext_sw_configuration_errors_raw
    hub: combox
    slave: 90
    register: 0x004C
    data_type: uint
  - name: conext_sw_battery_voltage
    hub: combox
    unit_of_measurement: V
    slave: 90
    register: 0x004E
    data_type: uint
    scale: 0.001
    precision: 1
  - name: conext_sw_battery_current
    hub: combox
    unit_of_measurement: A
    slave: 90
    register: 0x0050
    data_type: int
    scale: 0.001
    precision: 1
  - name: conext_sw_battery_power
    hub: combox
    unit_of_measurement: W
    slave: 90
    register: 0x0052
    data_type: int
  - name: conext_sw_battery_temperature
    hub: combox
    unit_of_measurement: °C
    slave: 90
    register: 0x0054
    data_type: uint
    scale: 0.01
    offset: -273
  - name: conext_sw_charger_status_raw
    hub: combox
    slave: 90
    register: 0x0055
    data_type: uint
  - name: conext_sw_invert_dc_current
    hub: combox
    unit_of_measurement: A
    slave: 90
    register: 0x0056
    data_type: uint
    scale: 0.001
    precision: 1
  - name: conext_sw_invert_dc_power
    hub: combox
    unit_of_measurement: W
    slave: 90
    register: 0x0058
    data_type: uint
  - name: conext_sw_charge_dc_current
    hub: combox
    unit_of_measurement: A
    slave: 90
    register: 0x005A
    data_type: uint
    scale: 0.001
    precision: 1
  - name: conext_sw_charge_dc_power
    hub: combox
    unit_of_measurement: W
    slave: 90
    register: 0x005C
    data_type: uint
  - name: conext_sw_charge_dc_power_percentage
    hub: combox
    unit_of_measurement: '%'
    slave: 90
    register: 0x005E
    data_type: uint
  - name: conext_sw_ac1_frequency
    hub: combox
    unit_of_measurement: Hz
    slave: 90
    register: 0x005F
    scale: 0.01
    data_type: uint
  - name: conext_sw_ac1_voltage
    hub: combox
    unit_of_measurement: V
    slave: 90
    register: 0x0060
    scale: 0.001
    precision: 1
    data_type: uint
  - name: conext_sw_ac1_input_current
    hub: combox
    unit_of_measurement: A
    slave: 90
    register: 0x0062
    scale: 0.001
    precision: 1
    data_type: uint
  - name: conext_sw_ac1_input_power
    hub: combox
    unit_of_measurement: W
    slave: 90
    register: 0x0064
    precision: 1
    data_type: uint
  - name: conext_sw_ac1_input_power_apparent
    hub: combox
    unit_of_measurement: VA
    slave: 90
    register: 0x0066
    precision: 1
    data_type: uint
  - name: conext_sw_ac1_l1_voltage
    hub: combox
    unit_of_measurement: V
    slave: 90
    register: 0x0068
    scale: 0.001
    precision: 1
    data_type: uint
  - name: conext_sw_ac1_l2_current
    hub: combox
    unit_of_measurement: A
    slave: 90
    register: 0x006A
    scale: 0.001
    precision: 1
    data_type: uint
  - name: conext_sw_ac1_l2_voltage
    hub: combox
    unit_of_measurement: V
    slave: 90
    register: 0x006C
    scale: 0.001
    precision: 1
    data_type: uint
  - name: conext_sw_ac1_l1_current
    hub: combox
    unit_of_measurement: A
    slave: 90
    register: 0x006E
    scale: 0.001
    precision: 1
    data_type: uint
  - name: conext_sw_ac1_voltage_qualified_raw
    hub: combox
    slave: 90
    register: 0x0070
    precision: 1
    data_type: uint
  - name: conext_sw_ac1_frequency_qualified_raw
    hub: combox
    slave: 90
    register: 0x0071
    precision: 1
    data_type: uint
  - name: conext_sw_ac1_qualified_duration
    hub: combox
    slave: 90
    register: 0x0072
    precision: 1
    unit_of_measurement: s
    data_type: uint
  - name: conext_sw_load_ac_voltage
    hub: combox
    unit_of_measurement: V
    slave: 90
    register: 0x0078
    scale: 0.001
    precision: 1
    data_type: uint
  - name: conext_sw_load_ac_l1_voltage
    hub: combox
    unit_of_measurement: V
    slave: 90
    register: 0x007A
    scale: 0.001
    precision: 1
    data_type: uint
  - name: conext_sw_load_ac_l2_voltage
    hub: combox
    unit_of_measurement: V
    slave: 90
    register: 0x007C
    scale: 0.001
    precision: 1
    data_type: uint
  - name: conext_sw_load_ac_l1_current
    hub: combox
    unit_of_measurement: A
    slave: 90
    register: 0x007E
    scale: 0.001
    precision: 1
    data_type: uint
  - name: conext_sw_load_ac_l2_current
    hub: combox
    unit_of_measurement: A
    slave: 90
    register: 0x0080
    scale: 0.001
    precision: 1
    data_type: uint
  - name: conext_sw_load_ac_current
    hub: combox
    unit_of_measurement: A
    slave: 90
    register: 0x0082
    scale: 0.001
    precision: 1
    data_type: uint
  - name: conext_sw_load_ac_power
    hub: combox
    unit_of_measurement: W
    slave: 90
    register: 0x0084
    precision: 1
    data_type: uint
  - name: conext_sw_load_ac_power_apparent
    hub: combox
    unit_of_measurement: VA
    slave: 90
    register: 0x008A
    precision: 1
    data_type: uint
  - name: conext_sw_load_ac_frequency
    hub: combox
    unit_of_measurement: Hz
    slave: 90
    register: 0x008C
    precision: 1
    data_type: uint
  - name: conext_sw_charge_dc_current
    hub: combox
    unit_of_measurement: A
    slave: 90
    register: 90
    scale: 0.001
    precision: 1
    data_type: uint
  - name: conext_sw_charge_dc_power
    hub: combox
    unit_of_measurement: W
    slave: 90
    register: 92
    data_type: uint
  - name: conext_sw_charge_dc_power_percentage
    hub: combox
    unit_of_measurement: '%'
    slave: 90
    register: 94
    data_type: uint
- platform: template
  sensors:
    conext_sw_device_state:
      value_template: >-
        {% if is_state('sensor.conext_sw_device_state_raw', '0') %}
          Hibernate
        {% elif is_state('sensor.conext_sw_device_state_raw', '1') %}
          Power Save
        {% elif is_state('sensor.conext_sw_device_state_raw', '2') %}
          Safe Mode
        {% elif is_state('sensor.conext_sw_device_state_raw', '3') %}
          Operating
        {% elif is_state('sensor.conext_sw_device_state_raw', '4') %}
          Diagnostic Mode
        {% elif is_state('sensor.conext_sw_device_state_raw', '5') %}
          Remote Power Off
        {% elif is_state('sensor.conext_sw_device_state_raw', '255') %}
          Data Not Available
        {% else %}
          ha-template-failure
        {% endif %}
    conext_sw_inverter_status:
      value_template: >-
        {% if is_state('sensor.conext_sw_inverter_status_raw', '1024') %}
          Invert
        {% elif is_state('sensor.conext_sw_inverter_status_raw', '1025') %}
          AC Pass Through
        {% elif is_state('sensor.conext_sw_inverter_status_raw', '1026') %}
          APS Only
        {% elif is_state('sensor.conext_sw_inverter_status_raw', '1027') %}
          Load Sense
        {% elif is_state('sensor.conext_sw_inverter_status_raw', '1028') %}
          Inverter Disabled
        {% elif is_state('sensor.conext_sw_inverter_status_raw', '1029') %}
          Load Sense Ready
        {% elif is_state('sensor.conext_sw_inverter_status_raw', '1030') %}
          Engaging Inverter
        {% elif is_state('sensor.conext_sw_inverter_status_raw', '1031') %}
          Invert Fault
        {% elif is_state('sensor.conext_sw_inverter_status_raw', '1032') %}
          Inverter Standby
        {% elif is_state('sensor.conext_sw_inverter_status_raw', '1033') %}
          Grid-Tied
        {% elif is_state('sensor.conext_sw_inverter_status_raw', '1034') %}
          Grid Support
        {% elif is_state('sensor.conext_sw_inverter_status_raw', '1035') %}
          Gen Support
        {% elif is_state('sensor.conext_sw_inverter_status_raw', '1036') %}
          Sell-to-Grid
        {% elif is_state('sensor.conext_sw_inverter_status_raw', '1037') %}
          Load Shaving
        {% elif is_state('sensor.conext_sw_inverter_status_raw', '1038') %}
          Grid Frequency Stabilization
        {% else %}
          ha-template-failure
        {% endif %}
    conext_sw_charger_status:
      value_template: >-
        {% if is_state('sensor.conext_sw_charger_status_raw', '768') %}
        Not Charging
        {% elif is_state('sensor.conext_sw_charger_status_raw', '769') %}
        Bulk
        {% elif is_state('sensor.conext_sw_charger_status_raw', '770') %}
        Absorption
        {% elif is_state('sensor.conext_sw_charger_status_raw', '771') %}
        Overcharge
        {% elif is_state('sensor.conext_sw_charger_status_raw', '772') %}
        Equalize
        {% elif is_state('sensor.conext_sw_charger_status_raw', '773') %}
        Float
        {% elif is_state('sensor.conext_sw_charger_status_raw', '774') %}
        No Float
        {% elif is_state('sensor.conext_sw_charger_status_raw', '775') %}
        Constant VI
        {% elif is_state('sensor.conext_sw_charger_status_raw', '776') %}
        Charger Disabled
        {% elif is_state('sensor.conext_sw_charger_status_raw', '777') %}
        Qualifying AC
        {% elif is_state('sensor.conext_sw_charger_status_raw', '778') %}
        Qualifying APS
        {% elif is_state('sensor.conext_sw_charger_status_raw', '779') %}
        Engaging Charger
        {% elif is_state('sensor.conext_sw_charger_status_raw', '780') %}
        Charge Fault
        {% elif is_state('sensor.conext_sw_charger_status_raw', '781') %}
        Charger Suspend
        {% elif is_state('sensor.conext_sw_charger_status_raw', '782') %}
        AC Good
        {% elif is_state('sensor.conext_sw_charger_status_raw', '783') %}
        APS Good
        {% elif is_state('sensor.conext_sw_charger_status_raw', '784') %}
        AC Fault
        {% elif is_state('sensor.conext_sw_charger_status_raw', '785') %}
        Charge
        {% elif is_state('sensor.conext_sw_charger_status_raw', '786') %}
        Absorption Exit Pending
        {% elif is_state('sensor.conext_sw_charger_status_raw', '787') %}
        Ground Fault
        {% elif is_state('sensor.conext_sw_charger_status_raw', '788') %}
        AC Good Pending
        {% else %}
        ha-template-failure
        {% endif %}
